import XCTest
@testable import Klyp

final class SensitiveContentTests: XCTestCase {
    func testTransientMarkerIsAlwaysSkipped() {
        let markers = SensitiveContent.markers(in: [SensitiveContent.transientType, "public.utf8-plain-text"])
        let decision = SensitiveContent.decision(
            for: markers,
            storeSensitiveItems: true,
            storeAutoGeneratedItems: true
        )

        XCTAssertEqual(decision, .skip(.transient))
    }

    func testConcealedIsSkippedByDefault() {
        let markers = SensitiveContent.markers(in: [SensitiveContent.concealedType])
        let decision = SensitiveContent.decision(
            for: markers,
            storeSensitiveItems: false,
            storeAutoGeneratedItems: false
        )

        XCTAssertEqual(decision, .skip(.concealed))
    }

    func testConcealedIsStoredSecurelyWhenEnabled() {
        let markers = SensitiveContent.markers(in: [SensitiveContent.concealedType])
        let decision = SensitiveContent.decision(
            for: markers,
            storeSensitiveItems: true,
            storeAutoGeneratedItems: false
        )

        XCTAssertEqual(decision, .captureSecure)
    }

    func testAutoGeneratedIsSkippedByDefault() {
        let markers = SensitiveContent.markers(in: [SensitiveContent.autoGeneratedType])
        let decision = SensitiveContent.decision(
            for: markers,
            storeSensitiveItems: false,
            storeAutoGeneratedItems: false
        )

        XCTAssertEqual(decision, .skip(.autoGenerated))
    }

    func testPlainContentIsCaptured() {
        let decision = SensitiveContent.decision(
            for: [],
            storeSensitiveItems: false,
            storeAutoGeneratedItems: false
        )

        XCTAssertEqual(decision, .capture)
    }
}
