import Foundation

enum SensitiveMarker: Hashable {
    case transient
    case autoGenerated
    case concealed
}

enum SensitiveDecision: Equatable {
    case capture
    case captureSecure
    case skip(SensitiveSkipReason)
}

enum SensitiveSkipReason: Equatable {
    case transient
    case autoGenerated
    case concealed
    case ignoredSource
}

enum SensitiveContent {
    static let transientType = "org.nspasteboard.TransientType"
    static let autoGeneratedType = "org.nspasteboard.AutoGeneratedType"
    static let concealedType = "org.nspasteboard.ConcealedType"

    static func markers(in typeIdentifiers: [String]) -> Set<SensitiveMarker> {
        var markers = Set<SensitiveMarker>()
        for type in typeIdentifiers {
            switch type {
            case transientType:
                markers.insert(.transient)
            case autoGeneratedType:
                markers.insert(.autoGenerated)
            case concealedType:
                markers.insert(.concealed)
            default:
                continue
            }
        }
        return markers
    }

    static func decision(
        for markers: Set<SensitiveMarker>,
        storeSensitiveItems: Bool,
        storeAutoGeneratedItems: Bool
    ) -> SensitiveDecision {
        if markers.contains(.transient) {
            return .skip(.transient)
        }
        if markers.contains(.concealed) {
            return storeSensitiveItems ? .captureSecure : .skip(.concealed)
        }
        if markers.contains(.autoGenerated), !storeAutoGeneratedItems {
            return .skip(.autoGenerated)
        }
        return .capture
    }

    static func redactedPreview(for item: ClipItem) -> String {
        switch item.kind {
        case .text, .richText:
            "Sensitive text"
        case .link:
            "Sensitive link"
        default:
            "Sensitive item"
        }
    }
}
