import AppKit
import Foundation

enum StatusBarClipFeedback {
    case captured
    case deduplicated
    case failed
}

@MainActor
struct AppEnvironment {
    let settings: AppSettings
    let historyStore: HistoryStore
    let pasteboardMonitor: PasteboardMonitor
    let pasteService: PasteService
    let globalHotkey: GlobalHotkey
    var onClipFeedback: ((StatusBarClipFeedback) -> Void)?

    init() {
        settings = AppSettings()
        historyStore = HistoryStore(settings: settings)
        pasteboardMonitor = PasteboardMonitor()
        pasteService = PasteService(
            historyStore: historyStore,
            monitor: pasteboardMonitor
        )
        globalHotkey = GlobalHotkey()

        settings.onLimitsChanged = { [historyStore] in
            historyStore.applyEvictionLimits()
        }
    }

    func start() {
        pasteboardMonitor.onCapture = { [self] item in
            handleCapture(item)
        }
        pasteboardMonitor.start()
    }

    func stop() {
        pasteboardMonitor.stop()
        globalHotkey.tearDown()
    }

    private func handleCapture(_ item: ClipItem) {
        if let source = item.source, settings.ignoredBundleIDs.contains(source.bundleIdentifier) {
            Log.info("Skipped clip from ignored source \(source.bundleIdentifier)")
            return
        }

        let markers = SensitiveContent.markers(in: Array(item.representations.keys))
        let decision = SensitiveContent.decision(
            for: markers,
            storeSensitiveItems: settings.storeSensitiveItems,
            storeAutoGeneratedItems: settings.storeAutoGeneratedItems
        )

        switch decision {
        case .capture:
            guard settings.isCaptureEnabled(for: item.kind) else {
                Log.info("Skipped clip type \(item.kind.rawValue) (disabled in settings)")
                return
            }
            let result = historyStore.add(item)
            handleAddResult(result)
        case .captureSecure:
            var secureItem = item
            secureItem.isSecure = true
            secureItem.previewText = SensitiveContent.redactedPreview(for: item)
            let result = historyStore.add(secureItem)
            handleAddResult(result)
        case let .skip(reason):
            Log.info("Skipped clip: \(reason)")
        }
    }

    private func handleAddResult(_ result: HistoryAddResult) {
        switch result {
        case .inserted:
            onClipFeedback?(.captured)
        case .deduplicated:
            onClipFeedback?(.deduplicated)
        case .failed:
            onClipFeedback?(.failed)
        }
    }
}
