import SwiftUI

struct PrivacySettings: View {
    @Bindable var settings: AppSettings

    var body: some View {
        Form {
            Section {
                Toggle("Store sensitive items", isOn: $settings.storeSensitiveItems)
                Text(
                    "Passwords and other concealed clipboard content are stored encrypted in the Keychain when enabled."
                )
                    .font(.caption)
                    .foregroundStyle(.secondary)
            } footer: {
                Text("Transient clipboard items are never stored.")
            }

            Section("Auto-generated content") {
                Toggle("Store auto-generated items", isOn: $settings.storeAutoGeneratedItems)
                Text("Some apps mark internal clipboard data as auto-generated. These are ignored by default.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
        }
        .formStyle(.grouped)
        .padding()
    }
}
