import Carbon
import Foundation
import Observation

struct AppSettingsDefaults {
    static let maxItems = 200
    static let maxBytes = 500 * 1024 * 1024
    static let maxAgeDays = 30
    static let secureMaxAgeHours = 24
    static let storeSensitiveItems = false
    static let storeAutoGeneratedItems = false
    static let captureText = true
    static let captureRichText = true
    static let captureImages = true
    static let captureFiles = true
    static let captureLinks = true
    static let hotkeyKeyCode = Int(kVK_ANSI_V)
    static let hotkeyModifiers = Int(cmdKey | shiftKey)
}

@MainActor
@Observable
final class AppSettings {
    var onLimitsChanged: (() -> Void)?
    var onHotkeyChanged: (() -> Void)?

    var maxItems: Int {
        didSet {
            UserDefaults.standard.set(maxItems, forKey: Keys.maxItems)
            onLimitsChanged?()
        }
    }

    var maxBytes: Int {
        didSet {
            UserDefaults.standard.set(maxBytes, forKey: Keys.maxBytes)
            onLimitsChanged?()
        }
    }

    var maxAgeDays: Int {
        didSet {
            UserDefaults.standard.set(maxAgeDays, forKey: Keys.maxAgeDays)
            onLimitsChanged?()
        }
    }

    var storeSensitiveItems: Bool {
        didSet { UserDefaults.standard.set(storeSensitiveItems, forKey: Keys.storeSensitiveItems) }
    }

    var storeAutoGeneratedItems: Bool {
        didSet { UserDefaults.standard.set(storeAutoGeneratedItems, forKey: Keys.storeAutoGeneratedItems) }
    }

    var ignoredBundleIDs: [String] {
        didSet { UserDefaults.standard.set(ignoredBundleIDs, forKey: Keys.ignoredBundleIDs) }
    }

    var captureText: Bool {
        didSet { UserDefaults.standard.set(captureText, forKey: Keys.captureText) }
    }

    var captureRichText: Bool {
        didSet { UserDefaults.standard.set(captureRichText, forKey: Keys.captureRichText) }
    }

    var captureImages: Bool {
        didSet { UserDefaults.standard.set(captureImages, forKey: Keys.captureImages) }
    }

    var captureFiles: Bool {
        didSet { UserDefaults.standard.set(captureFiles, forKey: Keys.captureFiles) }
    }

    var captureLinks: Bool {
        didSet { UserDefaults.standard.set(captureLinks, forKey: Keys.captureLinks) }
    }

    var hotkeyKeyCode: Int
    var hotkeyModifiers: Int

    var hotkeyCombination: HotkeyCombination {
        get {
            HotkeyCombination(
                keyCode: UInt32(hotkeyKeyCode),
                modifiers: UInt32(hotkeyModifiers)
            )
        }
        set {
            hotkeyKeyCode = Int(newValue.keyCode)
            hotkeyModifiers = Int(newValue.modifiers)
            persistHotkey()
            onHotkeyChanged?()
        }
    }

    var secureMaxAge: TimeInterval {
        TimeInterval(AppSettingsDefaults.secureMaxAgeHours * 60 * 60)
    }

    var evictionLimits: EvictionLimits {
        EvictionLimits(
            maxItems: maxItems,
            maxBytes: maxBytes,
            maxAge: maxAgeDays > 0 ? TimeInterval(maxAgeDays * 24 * 60 * 60) : 0
        )
    }

    func isCaptureEnabled(for kind: ClipItemKind) -> Bool {
        switch kind {
        case .text: captureText
        case .richText: captureRichText
        case .link: captureLinks
        case .image: captureImages
        case .file: captureFiles
        case .color: captureText
        }
    }

    init() {
        let defaults = UserDefaults.standard
        maxItems = defaults.object(forKey: Keys.maxItems) as? Int ?? AppSettingsDefaults.maxItems
        maxBytes = defaults.object(forKey: Keys.maxBytes) as? Int ?? AppSettingsDefaults.maxBytes
        maxAgeDays = defaults.object(forKey: Keys.maxAgeDays) as? Int ?? AppSettingsDefaults.maxAgeDays
        storeSensitiveItems = defaults.object(forKey: Keys.storeSensitiveItems) as? Bool
            ?? AppSettingsDefaults.storeSensitiveItems
        storeAutoGeneratedItems = defaults.object(forKey: Keys.storeAutoGeneratedItems) as? Bool
            ?? AppSettingsDefaults.storeAutoGeneratedItems
        ignoredBundleIDs = defaults.stringArray(forKey: Keys.ignoredBundleIDs) ?? []

        captureText = defaults.object(forKey: Keys.captureText) as? Bool ?? AppSettingsDefaults.captureText
        captureRichText = defaults.object(forKey: Keys.captureRichText) as? Bool ?? AppSettingsDefaults.captureRichText
        captureImages = defaults.object(forKey: Keys.captureImages) as? Bool ?? AppSettingsDefaults.captureImages
        captureFiles = defaults.object(forKey: Keys.captureFiles) as? Bool ?? AppSettingsDefaults.captureFiles
        captureLinks = defaults.object(forKey: Keys.captureLinks) as? Bool ?? AppSettingsDefaults.captureLinks
        hotkeyKeyCode = defaults.object(forKey: Keys.hotkeyKeyCode) as? Int ?? AppSettingsDefaults.hotkeyKeyCode
        hotkeyModifiers = defaults.object(forKey: Keys.hotkeyModifiers) as? Int ?? AppSettingsDefaults.hotkeyModifiers
    }

    private func persistHotkey() {
        UserDefaults.standard.set(hotkeyKeyCode, forKey: Keys.hotkeyKeyCode)
        UserDefaults.standard.set(hotkeyModifiers, forKey: Keys.hotkeyModifiers)
    }

    private enum Keys {
        static let maxItems = "maxItems"
        static let maxBytes = "maxBytes"
        static let maxAgeDays = "maxAgeDays"
        static let storeSensitiveItems = "storeSensitiveItems"
        static let storeAutoGeneratedItems = "storeAutoGeneratedItems"
        static let ignoredBundleIDs = "ignoredBundleIDs"
        static let captureText = "captureText"
        static let captureRichText = "captureRichText"
        static let captureImages = "captureImages"
        static let captureFiles = "captureFiles"
        static let captureLinks = "captureLinks"
        static let hotkeyKeyCode = "hotkeyKeyCode"
        static let hotkeyModifiers = "hotkeyModifiers"
    }
}
